# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_form_hex.ui'
#
# Created: Mon Feb 15 07:23:16 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Input_Form_Hex(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 400)
        Form.setMinimumSize(QtCore.QSize(800, 250))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_label.setFont(font)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.error_label = QtWidgets.QLabel(Form)
        self.error_label.setMinimumSize(QtCore.QSize(500, 0))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.value_table = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_table.sizePolicy().hasHeightForWidth())
        self.value_table.setSizePolicy(sizePolicy)
        self.value_table.setAutoScroll(True)
        self.value_table.setShowGrid(True)
        self.value_table.setWordWrap(False)
        self.value_table.setCornerButtonEnabled(True)
        self.value_table.setObjectName("value_table")
        self.value_table.setColumnCount(17)
        self.value_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.value_table.setHorizontalHeaderItem(16, item)
        self.value_table.horizontalHeader().setVisible(True)
        self.value_table.horizontalHeader().setCascadingSectionResizes(True)
        self.value_table.horizontalHeader().setDefaultSectionSize(35)
        self.value_table.horizontalHeader().setMinimumSectionSize(35)
        self.value_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.value_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.accept_button = QtWidgets.QPushButton(Form)
        self.accept_button.setMinimumSize(QtCore.QSize(150, 0))
        self.accept_button.setMaximumSize(QtCore.QSize(150, 27))
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout.addWidget(self.accept_button)
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setMinimumSize(QtCore.QSize(150, 27))
        self.exit_button.setMaximumSize(QtCore.QSize(150, 27))
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменение параметра"))
        self.info_label.setText(_translate("Form", "Изменение значения параметра возможно только в пределах выделенной для его хранения (в файле улье) памяти."))
        item = self.value_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "0"))
        item = self.value_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.value_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "2"))
        item = self.value_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "3"))
        item = self.value_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "4"))
        item = self.value_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "5"))
        item = self.value_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "6"))
        item = self.value_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "7"))
        item = self.value_table.horizontalHeaderItem(8)
        item.setText(_translate("Form", "8"))
        item = self.value_table.horizontalHeaderItem(9)
        item.setText(_translate("Form", "9"))
        item = self.value_table.horizontalHeaderItem(10)
        item.setText(_translate("Form", "a"))
        item = self.value_table.horizontalHeaderItem(11)
        item.setText(_translate("Form", "b"))
        item = self.value_table.horizontalHeaderItem(12)
        item.setText(_translate("Form", "c"))
        item = self.value_table.horizontalHeaderItem(13)
        item.setText(_translate("Form", "d"))
        item = self.value_table.horizontalHeaderItem(14)
        item.setText(_translate("Form", "e"))
        item = self.value_table.horizontalHeaderItem(15)
        item.setText(_translate("Form", "f"))
        item = self.value_table.horizontalHeaderItem(16)
        item.setText(_translate("Form", "ASCII"))
        self.accept_button.setText(_translate("Form", "Применить"))
        self.exit_button.setText(_translate("Form", "Отмена"))

